### ISSUE TITLE
flash is undefined

### ISSUE THREAD

**Issue by philip-sterne** [kevinyang372/codeEval#3]
When attempting to log in with an account which does not exist, an error is thrown.

It relates to the fact that `flash` is undefined:

https://github.com/kevinyang372/codeEval/blob/master/web/serve.py#L103

Logging in with the `example_admin_user@gmail.com` works fine.

**Comment by kevinyang372** [comment]
Thank you for the issue!

This has been solved in the latest commit: https://github.com/kevinyang372/codeEval/commit/e1f80d2e21b08d1ba4cf097cfe0cef11ddf60515

I am going to close this issue as it has already been solved.
